add radio
js-tasks-ru/htmlcss-20220811_daniil-maltsev pull request #17
Opened 2022-09-01 10:25 UTC by DAMaltsev

2022-09-01 10:26 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-01 15:48 UTC, GSemikozov requested changes

2022-09-01 15:48 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +.radio__input:checked ~ .radio__state .radio__icon {
.radio__icon описать отдельно, а при изменении состояния здесь менять только display (none -> block)

2022-09-04 18:32 UTC, DAMaltsev commented on 07-lection5/02-radio/radio.css
> +.radio__input:checked ~ .radio__state .radio__icon {
Поправил

2022-09-05 15:57 UTC, GSemikozov approved these changes

2022-09-05 15:57 UTC, merged