Burger menu
js-tasks-ru/htmlcss-20220811_daniil-maltsev pull request #20
Opened 2022-09-08 13:45 UTC by DAMaltsev

2022-09-08 13:46 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-08 14:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-08 15:50 UTC, GSemikozov requested changes

2022-09-08 15:50 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu-open {
блок не этого блока)
удалим.

2022-09-08 15:50 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu__toggler .toggler__state {
залазить в кишки одного компонента из другого нельзя - здесь проще создать новый компонент .theme-toggler (обертка над обычным .toggler)

2022-09-08 15:50 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu__toggler .toggler__state,
и тут

2022-09-08 15:50 UTC, GSemikozov commented on 09-lection7/01-burger-menu/index.html
> +        <button class="burger-menu__button">
элемент блока не может болтаться вне блока которому должен принадлежать. В целом, здесь достаточно использовать обычную кнопку `button button_primary`

2022-09-13 08:28 UTC, DAMaltsev commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu-open {
Поправил

2022-09-13 10:39 UTC, DAMaltsev commented on 09-lection7/01-burger-menu/index.html
> +        <button class="burger-menu__button">
Но ведь он тогда будет с bg и бордерами?

2022-09-13 10:45 UTC, DAMaltsev commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu__toggler .toggler__state {
Поправил

2022-09-13 10:46 UTC, DAMaltsev commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu__toggler .toggler__state,
Поправил

2022-09-13 10:50 UTC, DAMaltsev commented on 09-lection7/01-burger-menu/index.html
> +        <button class="burger-menu__button">
Добавил доп класс в компонент кнопки - button_transparent

2022-09-13 10:51 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-13 22:57 UTC, GSemikozov requested changes

2022-09-13 22:57 UTC, GSemikozov commented on 09-lection7/01-burger-menu/index.html
> +        <svg id="burger-menu-open" class="burger-menu__icon">
опять та же ошибка что и ранее - нельзя использовать элементы блока вне этого блока))
не нужно пробовать стилизовать внешнюю кнопку вызова меню через блока самого меню. Триггером может быть любая кнопка. В хедере - это будет такая иконка как сейчас здесь, но - конкретно при выполнении данной задачи (блок бургер-меню) - не нужно пытаться добавить кнопку из хедера, нам здесь не важно, как выглядит кнопка, которая открывает меню

2022-09-15 16:42 UTC, DAMaltsev commented on 09-lection7/01-burger-menu/index.html
> +        <svg id="burger-menu-open" class="burger-menu__icon">
Понял. Я просто удалил класс burger-menu__icon в коммите. Или надо прям полностью кнопку удалить?

2022-09-15 16:44 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-16 20:34 UTC, GSemikozov approved these changes

2022-09-16 20:34 UTC, merged