modal
js-tasks-ru/htmlcss-20220811_daniil-maltsev pull request #9
Opened 2022-08-24 21:53 UTC by DAMaltsev

2022-08-24 21:54 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-08-25 12:12 UTC, GSemikozov requested changes

2022-08-25 12:12 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +@import '../../03-lection1/01-button/button.css';
кнопка подключается в main.css, не нужно импортировать один компонент в другой

2022-08-25 12:12 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: absolute;
fixed

2022-08-25 12:12 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    width: 100%;
при выше описанном коде это уже лишнее

2022-08-25 12:12 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__background {
от этого элемента можно избавиться, если задать полупрозрачный фон сразу на уровне .modal через rgba

2022-08-25 12:49 UTC, DAMaltsev commented on 05-lection3/02-modal/modal.css
> +@import '../../03-lection1/01-button/button.css';
Готово

2022-08-25 12:50 UTC, DAMaltsev commented on 05-lection3/02-modal/modal.css
> +    position: absolute;
Поправил.

2022-08-25 12:53 UTC, DAMaltsev commented on 05-lection3/02-modal/modal.css
> +    width: 100%;
Убрал

2022-08-25 12:55 UTC, DAMaltsev commented on 05-lection3/02-modal/modal.css
> +.modal__background {
Убрал

2022-08-25 13:21 UTC, GSemikozov approved these changes

2022-08-25 13:22 UTC, merged